### ISSUE TITLE
Consider migrating away from rest-client?

### ISSUE THREAD

**Issue by dlackty** [pete2786/zapier_ruby#14]
Since rest-client hasn't been maintained for a while, and recently [there was a malicious version pushed to Rubygems.org](https://github.com/rest-client/rest-client/issues/713). I would suggest migrating away from this gem, and to something similar like httparty or typhoeus.

**Comment by pete2786** [comment]
Sure, it would be easy enough to switch the native http lib, since the requests are not terribly complicated. It would also kill a dependency.

**Comment by pete2786** [comment]
https://github.com/pete2786/zapier_ruby/pull/15 This should hopefully do the trick.
