### ISSUE TITLE
Cool project... anything else like it?

### ISSUE THREAD

**Issue by toobulkeh** [pete2786/zapier_ruby#8]
Just doing some research into webhook development and scalability in a Rails app. Your project came up in my search and I was wondering (since it's been a few years for activity) if there was anything learned from this project or scaled up for it?

Thanks!

**Comment by pete2786** [comment]
I'm not quite sure what you're asking. This project is a wrapper for Zapier integration, which uses it's webhooks. 

Webhooks can scale well with proper infrastructure, but this is just integrating third party webhooks.

**Comment by toobulkeh** [comment]
Sure -- was just curious if you were using this technique in production or if there was anything else built around it after awhile. Like webhook retry schedules, error handling, async out-of-banding, etc.

Just curious if it evolved at all unrelated to this code.
